services:
  myapp:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://root:root@db:5432/myapp_dev
    ports:
      - 3000:3000
    volumes:
      - ../:/myapp:cached

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=myapp_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: